name: Demo to create automatic PR

on:
  push:
    branches:
      - main

jobs:
  updatePR:
    runs-on: ubuntu-latest
    steps:
     - name: checking out code
       uses: actions/checkout@v2

     - name: extract git commit data
       run: |
         echo "Extracting Git commit data..."
         git log -1
         git log
         echo "Extraction complete."

     - name: Update PR
       run: |
         for commit_id in $(git rev-list main..HEAD); do
           echo "Creating PR for commit: $commit_id"
           echo $commit_id > COMMIT_ID
           echo $commit_id > AUTHOR
           git push origin HEAD:auto-pr-branch
           pr_title="Auto PR for commit: $commit_id"
           pr_body="This is an automatic PR for commit: $commit_id"
           gh pr create --title "$pr_title" --body "$pr_body" --base main --head auto-pr-branch --draft=false
         done
