name: Auto Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.TOKEN }}
        commit-message: 'Automated Pull Request'
        title: 'Automated Pull Request'
        branch: 'auto-pr-branch'
