name: Auto Create PR

on:
  push:
    branches:
      - '*'

jobs:
  autoCreatePR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config user.name "${{ secrets.GIT_COMMIT_AUTHOR_NAME }}"
          git config user.email "${{ secrets.GIT_COMMIT_AUTHOR_EMAIL }}"
          
      - name: Get User Info
        id: user_info
        run: |
          USER_NAME=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" "https://api.github.com/user" | jq -r '.name')
          echo "User Name: $USER_NAME"
        shell: bash

      - name: Extract Commit Message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit Message: $COMMIT_MESSAGE"
        id: commit_message

      - name: Create Pull Request
        run: |
          PR_TITLE="$USER_NAME created this PR for Commit ID: ${{ github.sha }}"
          PR_BODY="This is an automatically generated PR for commit ${{ github.sha }}.\n\n**Commit Message:**\n${{ steps.commit_message.outputs.commit_message }}"
          
          # Create a new branch for the pull request with the commit ID as the branch name
          git checkout -b "auto-branch-${{ github.sha }}"
          # Commit changes to the new branch
          git commit --allow-empty -m "${PR_TITLE}"
          # Push the new branch to the repository
          git push origin "auto-branch-${{ github.sha }}"
          # Create pull request using GitHub API
          PR_RESPONSE=$(curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -d '{"title":"'"${PR_TITLE}"'","body":"'"${PR_BODY}"'","head":"auto-branch-'"${{ github.sha }}"'","base":"main"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls")
          # Extract the pull request number from the API response
          PR_NUMBER=$(echo $PR_RESPONSE | jq -r '.number')
          echo "Pull Request created: ${{ github.repository }}/pull/$PR_NUMBER"
        env:
          PR_TITLE: ${{ github.sha }}
          PR_BODY: ${{ github.sha }}
