name: Demo to create automatic PR

on:
  push:
    branches:
      - main

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        run: |
          echo "Extracting Git commit data..."
          git log -1
          git log
          echo "Extraction complete."

      - name: Update author information
        run: |
          echo "${{ env.shivamnaik6574 }}" > AUTHOR
          git config user.name "${{ secrets.GIT_COMMIT_AUTHOR_NAME }}"
          git config user.email "${{ secrets.GIT_COMMIT_AUTHOR_EMAIL }}"

      - name: Raise PR for each commit
        run: |
          COMMITS=$(git rev-list --first-parent HEAD)
          for COMMIT in $COMMITS; do
            TITLE=$(git log --format=%B -n 1 $COMMIT | head -n 1)
            echo "Creating PR for commit $COMMIT with title: $TITLE"
            
            git cherry-pick $COMMIT
            git commit --allow-empty
            
            gh pr create --base main --head auto-pr-branch --title "$TITLE" --body "This is to show automatic PR creation" --base main
          done
