name: Auto PR on Commit

on:
  push:
    branches:
      - main
      - auto-pr-branch

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch complete commit history
        run: git fetch --unshallow || true

      - name: Extract git commit data
        run: |
          echo "Extracting Git commit data..."
          git log -1
          git log
          echo "Extraction complete."

      - name: Update author information
        run: echo ${{ env.shivamnaik6574 }} > AUTHOR

      - name: Create PR for each commit
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          
          for ((i = 1; i <= $COMMIT_COUNT; i++)); do
            COMMIT_HASH=$(git rev-parse HEAD~$i)
            PR_TITLE="Auto PR for commit $i"
            
            echo "Creating PR for commit $i with title: $PR_TITLE"
            
            GIT_COMMITTER_NAME="shivamnaik6574"
            GIT_COMMITTER_EMAIL="shivamnaik6574@gmail.com"
            
            git checkout -b auto-pr-branch-$i $COMMIT_HASH
            git push origin auto-pr-branch-$i
            
            gh pr create --base main --head auto-pr-branch-$i --title "$PR_TITLE" --body "This is an automatic PR for commit $i"
            
            echo "PR created for commit $i"
          done
